export { getCharacters, getCharacter } from './characters'
export { getComics, getComic } from './comics'
export { getCreators, getCreator } from './creators'
export { getEvents, getEvent } from './events'
export { getSeries, getSerie } from './series'
export { getStories, getStory } from './stories'
